wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.17
    start_time: 1717539615
    t:
      1:
      - 1
      3:
      - 13
      - 16
      4: 3.8.17
      5: 0.12.9
      8:
      - 5
algo_args:
  desc: null
  value:
    agent_args:
      action_space: Box(-0.6, 0.6, (13,), float32)
      adj: "[[1. 0. 0. ... 0. 0. 0.]\n [0. 1. 0. ... 0. 0. 0.]\n [0. 0. 1. ... 0.\
        \ 0. 0.]\n ...\n [0. 0. 0. ... 1. 0. 0.]\n [0. 0. 0. ... 0. 1. 0.]\n [0. 0.\
        \ 0. ... 0. 0. 1.]]"
      advantage_norm: true
      clip: 0.2
      embedding_sizes:
      - 26
      - 128
      - 128
      entropy_coeff: 0.0
      gamma: 0.99
      hidden_state_dim: 128
      lable_name: DMPO
      lamda: 0.5
      lr: 0.0005
      lr_p: 5.0e-05
      lr_v: 0.0005
      n_agent: 199
      n_minibatch: 1
      n_update_pi: 5
      n_update_v: 5
      observation_dim: 26
      p_args:
        edge_embed_dim: 64
        edge_hidden_size:
        - 128
        - 128
        n_conv: 1
        n_embedding: 0
        node_embed_dim: 64
        node_hidden_size:
        - 128
        - 128
        residual: true
        reward_coeff: 10.0
      parallel: false
      pi_args:
        activation: torch.nn.modules.activation.ReLU
        network: algorithms.models.MLP
        sizes:
        - -1
        - 256
        - 256
        - 16
        squash: false
      radius_p: 1
      radius_pi: 1
      radius_v: 1
      squeeze: true
      target_kl: 0.01
      use_gae_returns: false
      use_reduced_v: true
      use_rtg: true
      v_args:
        activation: torch.nn.modules.activation.ReLU
        network: algorithms.models.MLP
        sizes:
        - -1
        - 256
        - 256
        - 1
      v_coeff: 1.0
      v_thres: 0.0
    env_fn: algorithms.envs.Real_Power.Real_Power_Env
    load_pretrained_model: false
    max_episode_len: 240
    model_based: true
    model_batch_size: 256
    model_buffer_size: 15
    model_error_thres: 2.0e-10
    model_length_schedule: null
    model_prob: 0.5
    model_traj_length: 15
    model_update_length: 4
    model_validate_interval: 10
    n_inner_iter: 10
    n_iter: 25000
    n_model_update: 2000
    n_model_update_warmup: 20000
    n_test: 5
    n_traj: 2048
    n_warmup: 10
    pretrained_model: checkpoints/standard _makeRingAttenuation_MB_DPPOAgent_17293/2054577_-551.1475067236545.pt
    rollout_length: 240
    test_interval: 20
    test_length: 240
run_args:
  desc: null
  value:
    debug: false
    device: cuda:6
    init_checkpoint: null
    log_period: 20
    n_cpu: 0.25
    n_gpu: 0
    n_thread: 1
    name: DMPOAgent_44446
    parallel: false
    profiling: false
    radius_p: 1
    radius_pi: 1
    radius_v: 1
    save_period: 1800
    seed: 44446
    start_step: 0
    test: false
